version: '3.9'
services:
  database:
    container_name: 'familydatabase'
    image: mysql
    environment:
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 3
      interval: 15s
  familymemberapp:
    build: ./Application/familymemberApp
    ports:
      - "9010:9010"
    container_name: FamilyMemberAPP
    healthcheck:
      test: [ "CMD", "wget" ,"--spider", "http://localhost:9010/actuator/health"]
      timeout: 10s
      retries: 3
      interval: 10s
    depends_on:
      database:
        condition: service_healthy
  familyapp:
    build: ./Application/familyapp
    ports:
      - "9020:9020"
    container_name: FamilyAPP
    healthcheck:
      test: [ "CMD", "wget" ,"--spider", "http://localhost:9020/actuator/health" ]
      timeout: 10s
      retries: 3
      interval: 10s
    depends_on:
      familymemberapp:
        condition: service_healthy






