version: '3.9'
services:
  database:
    container_name: 'localdatabase'
    image: mysql
    restart: always
    environment:
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "9035:80"
    environment:
      - PMA_ARBITRARY=1

   



